version: 0.2

phases:
  build:
    commands:
      - npm install
      - npm run webpack
artifacts:
  files:
    - index.html
    - favicon.ico
    - Homan_Kevin_2018Jan16.pdf
    - styles/main.css
    - images/*
    - dist/bundle.js
