version: 0.2

phases:
  build:
    commands:
      - echo nothing to do yet
artifacts:
  files:
    - index.html
    - favicon.ico
    - Homan_Kevin_2018Jan16.pdf
    - styles/main.css
    - images/*
